StudentMApp/StudentMApp/Controllers/CourseAssignController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentMApp.BLL;
using StudentMApp.Model;

namespace StudentMApp.Controllers
{
    public class CourseAssignController : Controller
    {
        DeptManager dmanager = new DeptManager();
        TeacherManager tmanager = new TeacherManager();
        CourseManager cmanager = new CourseManager();
        CAManager caManager = new CAManager();
        
        // GET: /CourseAssign/
        public ActionResult Index()
        {
            return View();
        }

        //GET: /CourseAssign/
        public ActionResult AssignCourse()
        {
            ViewBag.deptList = dmanager.GetAllDept();
            return View();
        }

        public JsonResult CourseAssign(int deptId, int teacherId, int courseId, float courseCredit, float creditTaken, float dueCredit)
        {
            Teacher teacher = new Teacher();
            Course c = new Course();
            CourseAssign ca = new CourseAssign();

            //check if course is already assigned or not
            //var isCourseAssign = caManager.GetAllCourses().Where(a => a.CourseId == courseId && a.Courseflag == 1).ToList();
            var isCourseAssign = cmanager.GetAllCourses().Where(a => a.CId == courseId && a.CourseFlag == 1).ToList();
            if (isCourseAssign.Count > 0)
            {
                return Json(new { msg = "Course has already assigned" });
            }
            else
            {
                c.CId = courseId;
                c.DeptId = deptId;
                c.TeacherId = teacherId;
                c.CourseFlag = 1;

                //Teacher @default = tmanager.GetAllTeachers().FirstOrDefault(p => p.TId == c.TeacherId);
                //if (@default != null)
                //    c.TeacherName = @default.Name;

               
                //ca.DepartmentId = deptId;
                //ca.TeacherId = teacherId;
                //ca.CourseId = courseId;
                //Course courseDefault = cmanager.GetAllCourses().FirstOrDefault(m => m.CId == ca.CourseId);
                //if (courseDefault != null)
                //    ca.CourseSemester = courseDefault.SemName;
                //ca.Courseflag = 1;

                //after assigning course, it'll calculate the total assignCredit of a teacher 
                Teacher teacherDemo = tmanager.GetAllTeachers().FirstOrDefault(p => p.TId == teacherId);
                if (teacherDemo != null)
                {
                    float totalCredit = teacherDemo.TotalCredit + courseCredit;
                    teacher.TId = teacherId;
                    teacher.TotalCredit = totalCredit;
                }

                //assign course
                //string msg = caManager.AssignCourse(ca);
                int updateCourseStatus = cmanager.UpdateCourseStatus(c);
                int updateTeacherStatus = tmanager.UpdateTeacherStatus(teacher);

                if (updateCourseStatus > 0 && updateTeacherStatus > 0)
                {
                    string msg1 = "Assign Course Successfully";
                    
                    return Json(new { success = true, msg = msg1 }, JsonRequestBehavior.AllowGet);
                   // return Json(new { msg = "Assign Course Successfully" });
                }
                else if (cmanager.IsCourseAssign(teacherId, courseId))
                {
                    return Json(new { success = true, msg = "This course has already assigned" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true, msg = "Course has not assigned" }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(true);
        }

        //get all teachers by deptId
        public JsonResult GetTeacherByDeptId(int departmentId)
        {
            var teachers = tmanager.GetAllTeachers();
            var tList = teachers.Where(a => a.DeptID == departmentId).ToList();
            return Json(tList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTeacherById(int teacherId)
        {
            var teachers = tmanager.GetAllTeachers();
            var teacher = teachers.FirstOrDefault(m => m.TId == teacherId);
            teacher.DueCredit = teacher.Credit - teacher.TotalCredit;
            return Json(teacher, JsonRequestBehavior.AllowGet);
        }

        //get all course by deptId
        public JsonResult GetCourseByDeptId(int departmentId)
        {
            var courses = cmanager.GetAllCourses();
            var cList = courses.Where(a => a.DeptId == departmentId).ToList();
            return Json(cList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseById(int courseId)
        {
            var courses = cmanager.GetAllCourses();
            var course = courses.FirstOrDefault(m => m.CId == courseId);
            return Json(course, JsonRequestBehavior.AllowGet);
        }
    }
}

StudentMApp/StudentMApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentMApp.BLL;
using StudentMApp.Model;

namespace StudentMApp.Controllers
{
    public class CourseController : Controller
    {
        DeptManager dmanager = new DeptManager();
        SemesterManager sManager = new SemesterManager();

        CourseManager manager = new CourseManager();
        CAManager caManager = new CAManager();
        TeacherManager tManager = new TeacherManager();

        //
        // GET: /Course/
        public ActionResult Index()
        {
            //Todo: view course statics
            ViewBag.deptList = dmanager.GetAllDept();
            return View();
        }

        [HttpPost]
        public ActionResult Index(int departmentId)
        {
            //Todo: view course statics
            ViewBag.deptList = dmanager.GetAllDept();
            return View();
        }

        //Todo: view course statics
        public JsonResult GetDeptCourse(int departmentId)
        {
            var courses = manager.GetAllCourses();
            var cList = courses.Where(a => a.DeptId == departmentId).ToList();

            foreach (Course course1 in cList)
            {
                if (course1.CourseFlag == 0)
                {
                    course1.TeacherName = "Not assigned yet";
                }
            }
            return Json(cList, JsonRequestBehavior.AllowGet);
        }

        // GET: call when page load
        public ActionResult Save()
        {
            ViewBag.deptList = dmanager.GetAllDept();
            ViewBag.semList = sManager.GetAllInfo();
            return View();
        }

        //POST: call when button click 
        [HttpPost]
        public ActionResult Save(Course crs)
        {
            ViewBag.deptList = dmanager.GetAllDept();
            ViewBag.semList = sManager.GetAllInfo();
            List<Semester> sList = ViewBag.semList;

                if (ModelState.IsValid)
                {
                    ////addition: adding semester name
                    //if (crs.SemesterId != 0)
                    //{
                    //    Semester semester = sList.FirstOrDefault(p => p.SId == crs.SemesterId);
                    //    if (semester != null)
                    //        crs.SemName = semester.SName;
                    //}
                    ////end

                    
                    crs.TeacherId = 0;
                    //crs.TeacherName = ""; // addition: teacher's name
                    crs.CourseFlag = 0;
                    crs.Classflag = 0;

                    string msg = manager.SaveCourse(crs);
                    if (msg == "Saved")
                    {
                        ViewBag.Message = msg;
                    }
                    else
                    {
                        ViewBag.ErrorMessage = msg;
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = "Please enter all information";
                    return View();
                }
            return View();
        }


        // GET: /Unassign Course/
        public ActionResult UnassignCourse()
        {
            //Todo: create confirmation box 
            return View();
        }

        public JsonResult Unassign(bool flag)
        {
            int row1 = 0, row3 = 0;

            if (flag)
            {
                var teacherList = tManager.GetAllTeachers().Where(p => p.TotalCredit > 0).ToList();
                foreach (Teacher teacher in teacherList)
                {
                    teacher.TotalCredit = 0;
                    row1 = tManager.UpdateTeacherStatus(teacher);                
                }

                //var courseAssignList = caManager.GetAllCourses().Where(p => p.Courseflag == 1).ToList();
                //foreach (CourseAssign assign in courseAssignList)
                //{
                //    assign.Courseflag = 0;
                //    row2 = caManager.UpdateCourseStatus(assign);
                //}

                var courseList = manager.GetAllCourses().Where(p => p.CourseFlag == 1).ToList();
                foreach (Course course in courseList)
                {
                    course.CourseFlag = 0;
                    row3 = manager.UpdateCourseFlagStatus(course);
                }

                if (row1 > 0 && row3 > 0)
                {
                    return Json(new { msg = "Successfully unassign all courses" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { msg = "Already unassign all courses" }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { msg = "Failed to unassign" }, JsonRequestBehavior.AllowGet);
            }
            return Json(true);
        }
	}
}

StudentMApp/StudentMApp/Views/CourseAssign/AssignCourse.cshtml
@model StudentMApp.Model.CourseAssign

@{
    ViewBag.Title = "Course Assign";
}

<h3>Course Assign to Teacher</h3>
@Html.ActionLink("View Course Statics", "Index", "Course") | @Html.ActionLink("Menu", "USS", "Home")
<link href="~/Content/form-design.css" rel="stylesheet" />

<div class="container">
    <p id="message"></p>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true)


            <div class="form-group">
                <div class="col-md-12 input-group">
                    @Html.DropDownListFor(model => model.DepartmentId, new SelectList(ViewBag.deptList, "Id", "Name"), "Department", new { @id = "DepartmentId", required=""})
                    @Html.ValidationMessageFor(model => model.DepartmentId)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12 input-group">
                    @Html.DropDownListFor(model => model.TeacherId, new SelectList(string.Empty, "TId", "Name"), "Teacher", new { @id = "TeacherId", required = "" })
                    @Html.ValidationMessageFor(model => model.TeacherId)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12 input-group">
                    <input type="text" readonly class="form-control form-control-plaintext" id="CreditTaken" name="CreditTaken" placeholder="Credit Taken" required="">
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12 input-group">
                    <input type="text" readonly class="form-control form-control-plaintext" id="DueCredit" name="DueCredit" placeholder="Due Credit" required="">
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12 input-group">
                    @Html.DropDownListFor(model => model.CourseId, new SelectList(string.Empty, "CId", "CourseCode"), "Course", new { @id = "CourseId", required="" })
                    @Html.ValidationMessageFor(model => model.CourseId)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12 input-group">
                    <input type="text" readonly class="form-control form-control-plaintext" id="CourseName" name="CourseName" placeholder="Course Name" required="">
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12 input-group">
                    <input type="text" readonly class="form-control form-control-plaintext" id="CourseCredit" name="CourseCredit" placeholder="Course Credit" required="">
                </div>
            </div>

            <div class="form-group">
                <div>
                    <input type="submit" value="Assign" id="Assign" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>

@section scripts
{
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    
    <script>
        $(document).ready(function() {
            $("#DepartmentId").change(function() {

                var deptId = $("#DepartmentId").val();

                $("#TeacherId").empty();
                var json = { DepartmentId: deptId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTeacherByDeptId", "CourseAssign")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {
                        //alert(data);
                        $("#TeacherId").append('<option value=' + 0 + '>' + "Teacher" + '</option>');
                        $.each(data, function(key, value) {
                            //alert(key);
                            $("#TeacherId").append('<option value=' + value.TId + '>' + value.Name + '</option>');
                        });
                    }
                });


                $("#CourseId").empty();
                var json1 = { DepartmentId: deptId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseByDeptId", "CourseAssign")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json1),
                    success: function(data) {
                        //alert(data);
                        $("#CourseId").append('<option value=' + 0 + '>' + "Course" + '</option>');
                        $.each(data, function(key, value) {
                            //alert(key);
                            $("#CourseId").append('<option value=' + value.CId + '>' + value.CourseCode + '</option>');
                        });
                    }
                });
            });

            $("#TeacherId").change(function() {
                var teacher = $("#TeacherId").val();
                var jsonData = { TeacherId: teacher };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetTeacherById", "CourseAssign")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success: function(data) {
                        // alert(data.CreditTaken + " " + data.CreditLeft);
                        $("#CreditTaken").val(data.Credit);
                        $("#DueCredit").val(data.DueCredit);
                    }
                });
                return false;
            });


            $("#CourseId").change(function() {
                var course = $("#CourseId").val();
                var jsonData = { CourseId: course };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseById", "CourseAssign")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success: function(data) {
                        // alert(data.CreditTaken + " " + data.CreditLeft);
                        $("#CourseName").val(data.CourseName);
                        $("#CourseCredit").val(data.CourseCredit);
                    },

                });
                return false;
            });

            //var creditLeft = $("#DueCredit").val() - $("#CourseCredit").val();
            $("#Assign").click(function() {
                //alert("Hello");
                var teacherId = $("#TeacherId").val();
                var deptId = $("#DepartmentId").val();
                var courseId = $("#CourseId").val();
                var courseCredit = $("#CourseCredit").val();
                var creditTaken = $("#CreditTaken").val();
                var dueCredit = $("#DueCredit").val();

                var data1 = { teacherId: teacherId, deptId: deptId, courseId: courseId, courseCredit: courseCredit, creditTaken: creditTaken, dueCredit: dueCredit };
                //calculate remaining credit
                var creditLeft = dueCredit - courseCredit;
                ////if (deptId == 0 || teacherId == 0 || courseId == 0) {
                ////    alert("Please enter all information");
                ////}
                if (creditLeft >= 0) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("CourseAssign", "CourseAssign")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(data1),
                        dataType: "json",
                        async: false,
                        success: function (data) {
                            alert(data.msg);
                        }
                    });
                } else {
                    //alert("hello");
                    var r = confirm("More than the limit of teacher's credit. Are you sure you want to add this Course ?");
                    if (r == true) {
                        //alert("You pressed OK!");
                        $.ajax({
                            type: "POST",
                            url: '@Url.Action("CourseAssign", "CourseAssign")',
                            contentType: "application/json; charset=utf-8",
                            data: JSON.stringify(data),
                            dataType: "json",
                            success: function(data) {
                                if (data.msg != null) {
                                    alert(JSON.stringify(data.msg));
                                }
                            }
                        });
                    } else {
                        alert("Course is not assigned.");
                    }
                }
            });

        });
    </script>
}

StudentMApp/StudentMApp/Views/CourseAssign/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>