StudentMApp/StudentMApp/Controllers/AllocateClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentMApp.BLL;
using StudentMApp.Model;

namespace StudentMApp.Controllers
{
    public class AllocateClassController : Controller
    {
        DeptManager dmanager = new DeptManager();
        RoomManager rmanager = new RoomManager(); 
        CourseManager cmanager = new CourseManager();

        AllocateClassManager manager = new AllocateClassManager();
        ClassScheduleManager smanager = new ClassScheduleManager();
        //
        // GET: /view Class schedule/
        public ActionResult Index()
        {
            ViewBag.deptList = dmanager.GetAllDept();
            return View();
        }

        [HttpPost]
        // POST: /view Class schedule/
        public ActionResult Index(int departmentId)
        {
            ViewBag.deptList = dmanager.GetAllDept();
            return View();
        }

        public JsonResult GetDeptCourse(int departmentId)
        {
            var scheduleCourse = smanager.GetScheduleCourses();
            var courses = cmanager.GetAllCourses();
            List<Course> cList = courses.Where(a => a.DeptId == departmentId).ToList();

            foreach (Course course1 in cList)
            {
                var sCourse = scheduleCourse.Where(a => a.CourseId == course1.CId).ToList();

                if (sCourse.Count == 0 || course1.Classflag == 0)
                {
                    course1.Schedule = "Not scheduled yet";
                }
                if (sCourse.Count == 1 && course1.Classflag == 1)
                {
                    foreach (var c in sCourse)
                    {
                        course1.Schedule = c.Schedule;
                    }
                }
                if (sCourse.Count > 1 && course1.Classflag == 1)
                {
                    foreach (var c in sCourse)
                    {
                        course1.Schedule += c.Schedule + "\n\n";
                    }
                }
            }
            return Json(cList, JsonRequestBehavior.AllowGet);
        }


        AllocateClass aC = new AllocateClass();
        ClassSchedule schedule = new ClassSchedule();
        Course c1 = new Course();

        //Get
        public ActionResult AllocateClassroom()
        {
            ViewBag.deptList = dmanager.GetAllDept();
            ViewBag.roomList = rmanager.GetRooms();
            ViewBag.dayList = DayList();
            return View();
        }

        //post
        [HttpPost]
        public ActionResult AllocateClassroom(AllocateClass aclass)
        {
            ViewBag.deptList = dmanager.GetAllDept();
            ViewBag.roomList = rmanager.GetRooms();
            ViewBag.dayList = DayList();

                if (ModelState.IsValid)
                {
                    //calculate start time
                    var Time1 = aclass.StartTime;
                    var hour = Convert.ToInt32(Time1.Substring(0, 2));
                    var minute = Convert.ToInt32(Time1.Substring(3, 2));
                    var sFormat = Time1.Substring(6, 2);
                    TimeSpan startTime = new TimeSpan(hour, minute, 0);
                    
                    //calculate end time
                    var Time2 = aclass.EndTime;
                    var hour1 = Convert.ToInt32(Time2.Substring(0, 2));
                    var minute1 = Convert.ToInt32(Time2.Substring(3, 2));
                    var eFormat = Time2.Substring(6, 2);
                    TimeSpan endTime = new TimeSpan(hour1, minute1, 0);

                    if (startTime == endTime)
                    {
                        ViewBag.ErrorMessage = "Invalid Time";
                        return View();
                    }
                    else
                    {
                        aclass.StartTime = Time1.Substring(0, 2) + ":" + Time1.Substring(3, 2);
                        aclass.EndTime = Time2.Substring(0, 2) + ":" + Time2.Substring(3, 2);
                        aclass.StartTimeFormat = sFormat;
                        aclass.EndTimeFormat = eFormat;

                        //for Allocate classrom table
                        aC.DeptId = aclass.DeptId;
                        aC.CourseId = aclass.CourseId;
                        aC.RoomNo = aclass.RoomNo;
                        aC.DayName = aclass.DayName;
                        aC.StartTime = aclass.StartTime + " " + aclass.StartTimeFormat;
                        aC.StartTimeFormat = aclass.StartTimeFormat;
                        aC.EndTime = aclass.EndTime + " " + aclass.EndTimeFormat;
                        aC.EndTimeFormat = aclass.EndTimeFormat;

                        //for schedule table
                        var course = cmanager.GetAllCourses().FirstOrDefault(m => m.CId == aclass.CourseId);
                        schedule.CourseId = aclass.CourseId;
                        schedule.Schedule = "R. No: " + aclass.RoomNo + ", " + aclass.DayName + ", " + aC.StartTime + " - " + aC.EndTime;
                        schedule.ClassRoomFlag = 1;
                        
                        if (course != null)
                        {
                            //schedule.CourseCode = course.CourseCode;
                            //schedule.CourseName = course.CourseName;

                            //for course table
                            c1.CId = course.CId;
                            c1.DeptId = course.DeptId;
                            c1.Classflag = 1;
                        }
                       
                        string msgTxt = manager.AllocateClass(aC);
                        if (msgTxt == "saved" && smanager.SaveSchedule(schedule) > 0 && cmanager.UpdateClassStatus(c1) > 0)
                        {
                            ViewBag.Message = "Allocation Successful";
                        }
                        else
                        {
                            ViewBag.ErrorMessage = msgTxt;
                        }
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = "Room allocation fail";
                    return View();
                }

            return View();  
        }

        public JsonResult GetCourseByDeptId(int departmentId)
        {
            var courses = cmanager.GetAllCourses();
            var cList = courses.Where(a => a.DeptId == departmentId).ToList();
            return Json(cList, JsonRequestBehavior.AllowGet);
        }

        // GET: /Unallocate Classroom/
        public ActionResult UnalloClassroom()
        {
            //Todo: create confirmation box 
            return View();
        }

        public JsonResult Unallocate(bool flag)
        {
            int row1 = 0, row2 = 0, row3 = 0;

            if (flag)
            {
                //allocate class
                var classList = manager.GetAllocateClasses().Where(p => p.Classflag != 0).ToList();
                foreach (AllocateClass ac in classList)
                {
                    ac.Classflag = 0;
                    row1 = manager.UnalloClassroom(ac);
                }

                //schedule
                var sList = smanager.GetScheduleCourses().Where(p => p.ClassRoomFlag == 1).ToList();
                foreach (ClassSchedule assign in sList)
                {
                    assign.ClassRoomFlag = 0;
                    assign.Schedule = string.Empty;
                    row2 = smanager.UpdateSchedule(assign);
                }

                //course
                var courseList = cmanager.GetAllCourses().Where(p => p.Classflag == 1).ToList();
                foreach (Course course in courseList)
                {
                    course.Classflag = 0;
                    row3 = cmanager.UpdateClassFlagStatus(course);
                }

                if (row1 > 0 && row2 > 0 && row3 > 0)
                {
                    return Json(new { success = true, msg = "Successfully unallocate all classroom" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true, msg = "Already unallocated all classroom" }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                 return Json(new { success = true, msg = "Failed to unallocate classroom" }, JsonRequestBehavior.AllowGet);
            }
            return Json(true);
        }

        private List<Day> DayList()
        {
            List<Day> DayList = new List<Day>()
            {
                new Day{Id = 0, DayName = "Days"},
                new Day{Id = 1, DayName = "Sat"},
                new Day{Id = 2, DayName = "Sun"},
                new Day{Id = 3, DayName = "Mon"},
                new Day{Id = 4, DayName = "Tue"},
                new Day{Id = 5, DayName = "Wed"},
                new Day{Id = 6, DayName = "Thurs"},
                new Day{Id = 6, DayName = "Fri"} 
            };
            return DayList;
        }
	}
}

StudentMApp/StudentMApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentMApp.BLL;
using StudentMApp.Model;

namespace StudentMApp.Controllers
{
    public class CourseController : Controller
    {
        DeptManager dmanager = new DeptManager();
        SemesterManager sManager = new SemesterManager();

        CourseManager manager = new CourseManager();
        CAManager caManager = new CAManager();
        TeacherManager tManager = new TeacherManager();

        //
        // GET: /Course/
        public ActionResult Index()
        {
            //Todo: view course statics
            ViewBag.deptList = dmanager.GetAllDept();
            return View();
        }

        [HttpPost]
        public ActionResult Index(int departmentId)
        {
            //Todo: view course statics
            ViewBag.deptList = dmanager.GetAllDept();
            return View();
        }

        //Todo: view course statics
        public JsonResult GetDeptCourse(int departmentId)
        {
            var courses = manager.GetAllCourses();
            var cList = courses.Where(a => a.DeptId == departmentId).ToList();

            foreach (Course course1 in cList)
            {
                if (course1.CourseFlag == 0)
                {
                    course1.TeacherName = "Not assigned yet";
                }
            }
            return Json(cList, JsonRequestBehavior.AllowGet);
        }

        // GET: call when page load
        public ActionResult Save()
        {
            ViewBag.deptList = dmanager.GetAllDept();
            ViewBag.semList = sManager.GetAllInfo();
            return View();
        }

        //POST: call when button click 
        [HttpPost]
        public ActionResult Save(Course crs)
        {
            ViewBag.deptList = dmanager.GetAllDept();
            ViewBag.semList = sManager.GetAllInfo();
            List<Semester> sList = ViewBag.semList;

                if (ModelState.IsValid)
                {
                    ////addition: adding semester name
                    //if (crs.SemesterId != 0)
                    //{
                    //    Semester semester = sList.FirstOrDefault(p => p.SId == crs.SemesterId);
                    //    if (semester != null)
                    //        crs.SemName = semester.SName;
                    //}
                    ////end

                    
                    crs.TeacherId = 0;
                    //crs.TeacherName = ""; // addition: teacher's name
                    crs.CourseFlag = 0;
                    crs.Classflag = 0;

                    string msg = manager.SaveCourse(crs);
                    if (msg == "Saved")
                    {
                        ViewBag.Message = msg;
                    }
                    else
                    {
                        ViewBag.ErrorMessage = msg;
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = "Please enter all information";
                    return View();
                }
            return View();
        }


        // GET: /Unassign Course/
        public ActionResult UnassignCourse()
        {
            //Todo: create confirmation box 
            return View();
        }

        public JsonResult Unassign(bool flag)
        {
            int row1 = 0, row3 = 0;

            if (flag)
            {
                var teacherList = tManager.GetAllTeachers().Where(p => p.TotalCredit > 0).ToList();
                foreach (Teacher teacher in teacherList)
                {
                    teacher.TotalCredit = 0;
                    row1 = tManager.UpdateTeacherStatus(teacher);                
                }

                //var courseAssignList = caManager.GetAllCourses().Where(p => p.Courseflag == 1).ToList();
                //foreach (CourseAssign assign in courseAssignList)
                //{
                //    assign.Courseflag = 0;
                //    row2 = caManager.UpdateCourseStatus(assign);
                //}

                var courseList = manager.GetAllCourses().Where(p => p.CourseFlag == 1).ToList();
                foreach (Course course in courseList)
                {
                    course.CourseFlag = 0;
                    row3 = manager.UpdateCourseFlagStatus(course);
                }

                if (row1 > 0 && row3 > 0)
                {
                    return Json(new { msg = "Successfully unassign all courses" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { msg = "Already unassign all courses" }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { msg = "Failed to unassign" }, JsonRequestBehavior.AllowGet);
            }
            return Json(true);
        }
	}
}

StudentMApp/StudentMApp/Views/AllocateClass/AllocateClassroom.cshtml
@model StudentMApp.Model.AllocateClass

@{
    ViewBag.Title = "AllocateClassroom";
}

<h3>Allocate Classroom</h3>
@Html.ActionLink("View Allocated classes", "Index", "AllocateClass") | @Html.ActionLink("Menu", "USS", "Home")
<link href="~/Content/form-design.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        @if (ViewBag.Message != null)
        {
            <div class="alert alert-success alert-dismissable" id="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
                @ViewBag.Message
            </div>
        }

        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger alert-dismissable" id="erroralert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
                @ViewBag.ErrorMessage
            </div>
        }
       
        <div class="form-group">
            <div class="col-md-12 input-group">
                @Html.DropDownListFor(model => model.DeptId, new SelectList(ViewBag.deptList, "Id", "Name"), "Department", new { htmlAttributes = new { @class = "form-control", @id = "DeptId" }, required="" })
                @Html.ValidationMessageFor(model => model.DeptId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                @Html.DropDownListFor(model => model.CourseId, new SelectList(string.Empty, "CId", "CourseName"), "Courses", new { htmlAttributes = new { @class = "form-control", @id = "CourseId" }, required="" })
                @Html.ValidationMessageFor(model => model.CourseId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                @Html.DropDownListFor(model => model.RoomNo, new SelectList(ViewBag.roomList, "RoomNo", "RoomNo"), "Room No", new { htmlAttributes = new { @class = "form-control", @id = "RoomNo" }, required="" })
                @Html.ValidationMessageFor(model => model.RoomNo)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                @Html.DropDownListFor(model => model.DayName, new SelectList(ViewBag.dayList, "DayName", "DayName"), new { htmlAttributes = new { @class = "form-control", @id = "DayName" }, required="" })
                @Html.ValidationMessageFor(model => model.DayName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-3 input-group">
                <input type="text" readonly class="form-control-plaintext" name="StartTime" placeholder="StartTime" id="StartTime" required="" style="width: 260px">
            </div>
            <div class="col-md-9"></div>
        </div>

        <div class="form-group">
            <div class="col-md-3 input-group">
                <input type="text" readonly class="form-control-plaintext" name="EndTime" placeholder="EndTime" id="EndTime" required="" style="width: 260px">
            </div>
            <div class="col-md-9"></div>
        </div>

        <div class="form-group">
            <div>
                <input type="submit" value="Allocate" id="allocate" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />       
    
    <script>
        $(document).ready(function() {
            $("#DeptId").change(function() {
                var DeptId = $("#DeptId").val();

                $("#CourseId").empty();
                var json = { departmentId: DeptId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseByDeptId", "AllocateClass")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {
                        $("#CourseId").append('<option value=' + 0 + '>' + "Courses" + '</option>');
                        $.each(data, function(key, value) {
                            $("#CourseId").append('<option value=' + value.CId + '>' + value.CourseName + '</option>');
                        });
                    }
                });
                return false;
            });

            $('#StartTime').timepicker({
                format: 'hh.MM.TT'
            });
            $('#EndTime').timepicker({
                format: 'hh.MM.TT'
            });

            $("#allocate").click(function() {

            });

            $("#alert").click(function() {
                $("#alert").hide();

            });

            $("#erroralert").click(function() {
                $("#erroralert").hide();
            });
        });
    </script>

}

StudentMApp/StudentMApp/Views/AllocateClass/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h3>View Class Schedule and Room Allocation Information</h3>
@Html.ActionLink("Allocate Classroom", "AllocateClassroom", "AllocateClass") | @Html.ActionLink("Menu", "USS", "Home")
<link href="~/Content/form-design.css" rel="stylesheet" />

@using (Html.BeginForm("Index", "Course", FormMethod.Get))
{
    <hr/>
    <br/>
    <table cellspacing="2" cellpadding="2">
        <tr>
            @*<td><label for="departmentId">Department</label> </td>*@
            <td>
                <select name="departmentId" id="departmentId" style="width: 300px">
                    <option value="0">Departments</option>
                    @foreach (var c in ViewBag.deptList)
                    {
                        <option value="@c.Id">@c.Name</option>
                    }
                </select>
            </td>
        </tr>
    </table>

    <div id="divData" class="container">
        <br />
        <table class="table table-hover" id="tblData">
            <thead>
                <tr>
                    <th align="left" class="Courseth">Course Code</th>
                    <th align="left" class="Courseth">Name / Title</th>
                    <th align="left" class="Courseth">Schedule Info</th>
                </tr>
            </thead>

            <tbody id="tblBody"></tbody>
        </table>

        <p style="color: red">@ViewBag.msg</p>
    </div>
  
    @*<div>
        <table id="tblCourse" class="tblCourse">
            <thead>
                <tr>
                    <th align="left" class="Courseth">Course Code</th>
                    <th align="left" class="Courseth">Name/Title</th>
                    <th align="left" class="Courseth">Schedule Info</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>*@



    @*<style type="text/css">
        .tblCourse {
            font-family: verdana,arial,sans-serif;
            font-size: 11px;
            color: #333333;
            border-width: 1px;
            border-color: #666666;
            border-collapse: collapse;
        }

        .Courseth {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #dedede;
        }

        .coursetd {
            border-width: 1px;
            padding: 8px;
            border-style: solid;
            border-color: #666666;
            background-color: #ffffff;
        }
    </style>*@


    @section scripts{
        <script src="~/Scripts/jquery-3.1.1.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $("#departmentId").change(function () {
                    var catId = $("#departmentId").val();
                    $("#tblData tbody tr").remove();
                    var json = { departmentId: catId };
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("GetDeptCourse", "AllocateClass")',
                        contentType: 'application/json; charset=utf-8',
                        data: JSON.stringify(json),
                        success: function (data) {
                            var items = '';
                            $.each(data, function (i, item) {
                                var rows =
                                    "<tr>"
                                        + "<td class='coursetd'>" + item.CourseCode + "</td>"
                                        + "<td class='coursetd'>" + item.CourseName + "</td>"
                                        + "<td class='coursetd'>" + item.Schedule + "</td>"
                                        + "</tr>";
                                $('#tblData tbody').append(rows);
                            });
                        },
                        error: function (ex) {
                            var r = jQuery.parseJSON(response.responseText);
                            alert("Message: " + r.Message);
                            alert("StackTrace: " + r.StackTrace);
                            alert("ExceptionType: " + r.ExceptionType);
                        }
                    });
                    return false;
                });
            });
        </script>

    }

}

StudentMApp/StudentMApp/Views/AllocateClass/UnalloClassroom.cshtml
@{
    ViewBag.Title = "UnalloClassroom";
}

<h3>Unallocate Classroom</h3>
<link href="~/Content/form-design.css" rel="stylesheet" />
@Html.ActionLink("Back to Menu", "USS", "Home")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Unallocate Rooms" class="btn btn-default" id="btnUnallocate" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>

    <script>
        $(document).ready(function() {
            $("#btnUnallocate").click(function() {
                var r = confirm("Are you sure to unallocate all classroom?");
                if (r == true) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Unallocate", "AllocateClass")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify({ flag: true }),
                        dataType: "json",
                        async: false,
                        success: function(data) {
                            if (data.msg != null) {
                                alert(data.msg);
                            }
                            if (data == true) {
                               console.log("true");
                               alert("Successfully unallocate all classroom.");
                            }
                        }
                    });
                } else {
                    alert("Failed.");
                }
            });

            $("#alert").click(function() {
                $("#alert").hide();
            });

            $("#erroralert").click(function() {
                $("#erroralert").hide();
            });

        });
    </script>
}