StudentMApp/StudentMApp/Controllers/StudentResultController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentMApp.BLL;
using StudentMApp.Model;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Font = iTextSharp.text.Font;


namespace StudentMApp.Controllers
{
    public class StudentResultController : Controller
    {
        DeptManager dmanager = new DeptManager();
        StudentManager smanager = new StudentManager();
        CourseManager cmanager = new CourseManager();

        EnrollStudentManager esManager = new EnrollStudentManager();
        //StudentResultManager manager = new StudentResultManager();
        
        // GET: /StudentResult/
        public ActionResult Index()
        {
            ViewBag.RegNoList = smanager.GetAllRegNo();
            return View();
        }

        // POST: /StudentResult/
        [HttpPost]
        public ActionResult Index(StudentResult student)
        {
            ViewBag.RegNoList = smanager.GetAllRegNo();
            foreach (Student sr in ViewBag.RegNoList)
            {
                if (sr.Id == student.RegNo)
                {
                    student.StudentRegNo = sr.RegNo;
                    break;
                }
            }

            var courses = esManager.GetStudentResult();
            var cList = courses.Where(a => a.RegNo == student.RegNo).ToList();

            foreach (StudentResult course1 in cList)
            {
                if (course1.GradeLetter == "0")
                {
                    course1.GradeLetter = "Not graded yet";
                }
            }

            if (student != null && cList.Count != 0)
            {
                //generate pdf with info
                try
                {
                    Document pdfDoc = new Document(PageSize.A4, 25, 10, 25, 10);               
                    PdfWriter pdfWriter = PdfWriter.GetInstance(pdfDoc, Response.OutputStream);
                    Phrase phrase = null;     
                    PdfPTable table = null;
                   
                    pdfDoc.Open();

                    //header table
                    table = new PdfPTable(2);
                    table.TotalWidth = 500f;
                    table.LockedWidth = true;
                    table.SetWidths(new float[] { 0.3f, 0.7f });
                    pdfDoc.Add(table);

                    //Name and Address
                    phrase = new Phrase();
                    phrase.Add(new Chunk("Southeast University\n\n", FontFactory.GetFont("Arial", 16, iTextSharp.text.Font.BOLD, iTextSharp.text.BaseColor.BLACK)));
                    phrase.Add(new Chunk("251/A and 252, Tejgaon Industrial Area\n", FontFactory.GetFont("Arial", 8, iTextSharp.text.Font.NORMAL, iTextSharp.text.BaseColor.BLACK)));
                    phrase.Add(new Chunk("Dhaka-1208, Bangladesh\n", FontFactory.GetFont("Arial", 8, iTextSharp.text.Font.NORMAL, iTextSharp.text.BaseColor.BLACK)));
                    pdfDoc.Add(phrase);

                    //Student info
                    PdfPTable table1 = new PdfPTable(2);
                    PdfPCell cell1 = new PdfPCell(new Phrase("Student Information"));
                    cell1.Colspan = 2;
                    cell1.HorizontalAlignment = Element.ALIGN_CENTER;
                    table1.AddCell(cell1);

                    table1.AddCell("Student Reg No. "); table1.AddCell(student.StudentRegNo);
                    table1.AddCell("Name "); table1.AddCell(student.StudentName);
                    table1.AddCell("Email "); table1.AddCell(student.StudentEmail);
                    table1.AddCell("Department "); table1.AddCell(student.Department);
                    pdfDoc.Add(table1);

                    Paragraph pText = new Paragraph("\n\n\n");
                    pdfDoc.Add(pText);

                    //Course info
                    PdfPTable table2 = new PdfPTable(3);
                    PdfPCell cell2 = new PdfPCell(new Phrase("Course Information"));
                    cell2.Colspan = 3;
                    cell2.HorizontalAlignment = Element.ALIGN_CENTER;
                    table2.AddCell(cell2);

                   //header
                    table2.AddCell("Course Code");
                    table2.AddCell("Course Name");
                    table2.AddCell("Grade");
                    
                    foreach (StudentResult test in cList)
                    {
                        table2.AddCell(test.courseCode);
                        table2.AddCell(test.courseName);
                        table2.AddCell(test.GradeLetter);
                        //count++;
                    }
                    pdfDoc.Add(table2);

                    pText = new Paragraph("\n\n");
                    pdfDoc.Add(pText);

                    pdfWriter.CloseStream = false;
                    pdfDoc.Close();

                    //create pdf
                    Response.Buffer = true;
                    Response.ContentType = "application/pdf";
                    Response.AddHeader("content-disposition", "attachment;filename=Student_Result.pdf");
                    Response.Cache.SetCacheability(HttpCacheability.NoCache);
                    Response.Write(pdfDoc);
                }
                catch (Exception ex)
                {
                    Response.Write(ex.Message);
                }
            }
            return View();
        }

        public JsonResult GetStudentResult(int RegNo)
        {
            var courses = esManager.GetStudentResult();
            var cList = courses.Where(a => a.RegNo == RegNo).ToList();

            if (cList.Count == 0)
            {         
                return Json(cList);
            }

            foreach (StudentResult course1 in cList)
            {
                if (course1.GradeLetter == "0")
                {
                    course1.GradeLetter = "Not graded yet";
                }
            }
            return Json(cList, JsonRequestBehavior.AllowGet);
        }

        Student s = new Student();
        Department d = new Department();
        Course c = new Course();

        //GET: /StudentResult/
        public ActionResult StudentResult()
        {
            ViewBag.RegNoList = smanager.GetAllRegNo();
            ViewBag.GradeList = GradeList();
            return View();
        }

        [HttpPost]
        // POST: /StudentResult/
        public ActionResult StudentResult(StudentResult student)
        {
            ViewBag.RegNoList = smanager.GetAllRegNo();
            ViewBag.GradeList = GradeList();
            if (student.courseId == 0 || student.GradeLetter == "--Select--")
            {
                ViewBag.ErrorMessage = "Course/Grade hasn't selected yet";
                return View();
            }

            if (ModelState.IsValid)
            {
                var student1 = smanager.GetAllStudents().FirstOrDefault(m => m.Id == student.RegNo);
                if (student1 != null) student.deptId = student1.DeptId;

                string testmsg = esManager.SaveResultToStudent(student);
                if (testmsg == "Saved")
                {
                    ViewBag.Message = testmsg;
                    return View();
                }
                else
                {
                    ViewBag.ErrorMessage = testmsg;
                    return View();
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Please enter all information";
                return View();
            }

            return View();
        }



        //get student info
        public JsonResult GetStudentById(int RegNo)
        {
            var students = smanager.GetAllStudents();
            var student = students.FirstOrDefault(m => m.Id == RegNo);
            

            List<Department> deptList = dmanager.GetAllDept();
            foreach (Department d in deptList)
            {
                if (d.Id == student.DeptId)
                {
                    student.DeptName = d.Name;
                    break;
                }
            }
            return Json(student, JsonRequestBehavior.AllowGet);
        }



        //get all course by regId
        public JsonResult GetCourseByRegId(int RegNo)
        {
            var courses = esManager.GetStudentCourse(RegNo);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }

        private List<Grade> GradeList()
        {
            List<Grade> GradeList = new List<Grade>()
            {
                new Grade{Id = 0, GradeName = "Grades"},
                new Grade{Id = 1, GradeName = "A+"},
                new Grade{Id = 2, GradeName = "A"},
                new Grade{Id = 3, GradeName = "A-"},
                new Grade{Id = 4, GradeName = "B+"},
                new Grade{Id = 5, GradeName = "B"},
                new Grade{Id = 6, GradeName = "B-"},
                new Grade{Id = 7, GradeName = "C+"},
                new Grade{Id = 8, GradeName = "C"},
                new Grade{Id = 9, GradeName = "C-"},
                new Grade{Id = 10, GradeName = "D+"},
                new Grade{Id = 11, GradeName = "D"},
                new Grade{Id = 12, GradeName = "D-"},
                new Grade{Id = 13, GradeName = "F"}
            };

            return GradeList;
        }


	}
}

StudentMApp/StudentMApp/Views/StudentResult/Index.cshtml
@model StudentMApp.Model.StudentResult
@{
    ViewBag.Title = "Index";
}

<h3>View Student Result</h3>
@Html.ActionLink("Menu", "USS", "Home") | @Html.ActionLink("Save Student Result", "StudentResult", "StudentResult")
<link href="~/Content/form-design.css" rel="stylesheet" />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-12 input-group">
                @Html.DropDownListFor(model => model.RegNo, new SelectList(ViewBag.RegNoList, "Id", "RegNo"), "Student Registration No", new { htmlAttributes = new { @class = "form-control", @id = "RegNo" }, required="" })
                @Html.ValidationMessageFor(model => model.RegNo)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                <input type="text" readonly class="form-control-plaintext" id="StudentName" placeholder="Student Name" required="">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                <input type="text" readonly class="form-control-plaintext" id="StudentEmail" placeholder="Student Email" required="">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                <input type="text" readonly class="form-control-plaintext" id="Department" placeholder="Department" required="">
            </div>
        </div>
        
        <div class="form-group">
            <div>
                <input type="submit" value="Make PDF" class="btn btn-success" id="pdf"/>
            </div>
        </div>

        <div id="divData" class="container">
            <br/>
            <table id="tblData" class="table table-hover">
                <thead>
                    <tr>
                        <th align="left" class="Courseth">Course Code</th>
                        <th align="left" class="Courseth">Name / Title</th>
                        <th align="left" class="Courseth">Grade</th>
                    </tr>
                </thead>
                <tbody id="tblBody"></tbody>
            </table>
            <p id="msg" class="text-center" style="font-weight: bold"></p>
        </div>
        
        @*<style type="text/css">
            .tblCourse {
                font-family: verdana,arial,sans-serif;
                font-size: 11px;
                color: #333333;
                border-width: 1px;
                border-color: #666666;
                border-collapse: collapse;
            }

            .Courseth {
                border-width: 1px;
                padding: 8px;
                border-style: solid;
                border-color: #666666;
                background-color: #dedede;
            }

            .coursetd {
                border-width: 1px;
                padding: 8px;
                border-style: solid;
                border-color: #666666;
                background-color: #ffffff;
            }
        </style>*@
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>

        $(document).ready(function() {

            $("#RegNo").change(function() {
                var student = $("#RegNo").val();
                var jsonData = { RegNo: student };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentById", "StudentResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success: function(data) {
                            $("#StudentName").val(data.Name);
                            $("#StudentEmail").val(data.Email);
                            $("#Department").val(data.DeptName); 
                    }
                });
                return false;
            });


            $("#RegNo").change(function() {
                var catId = $("#RegNo").val();
                $("#tblData tbody tr").remove();
                var json = { RegNo: catId };
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("GetStudentResult", "StudentResult")',
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify(json),
                    success: function (data) {
                        if (!$.trim(data))
                        {
                            $("#msg").html("Data not found");
                        }
                        $.each(data, function(i, item) {
                            var rows =
                                "<tr>"
                                    + "<td class='coursetd'>" + item.courseCode + "</td>"
                                    + "<td class='coursetd'>" + item.courseName + "</td>"
                                    + "<td class='coursetd'>" + item.GradeLetter + "</td>"
                                    + "</tr>";
                            $('#tblData tbody').append(rows);
                            $("#msg").empty();
                        });
                    },
                    error: function(ex) {
                        var r = jQuery.parseJSON(response.responseText);
                        alert("Message: " + r.Message);
                        alert("StackTrace: " + r.StackTrace);
                        alert("ExceptionType: " + r.ExceptionType);
                    }
                });
                return false;
            });
        });


//$("#pdf").click(function () {

        //    $("#StudentName").val("");
        //    $("#StudentEmail").val("");
        //    $("#Department").val("");
        //    $("#tblCourse").val("");
        //});


    </script>
}

StudentMApp/StudentMApp/Views/StudentResult/StudentResult.cshtml
@model StudentMApp.Model.StudentResult
@{
    ViewBag.Title = "StudentResult";
    string success = ViewBag.Message;
    string error = ViewBag.ErrorMessage;
}

<h3>Student Result</h3>
@Html.ActionLink("Menu", "USS", "Home") | @Html.ActionLink("View Student Result", "Index", "StudentResult")
<link href="~/Content/form-design.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if (ViewBag.Message != null)
        {
            <div class="alert alert-success alert-dismissable" id="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
                @success
            </div>
        }

        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger alert-dismissable" id="erroralert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">x</a>
                @error
            </div>
        }

        <div class="form-group">
            <div class="col-md-12 input-group">
                @Html.DropDownListFor(model => model.RegNo, new SelectList(ViewBag.RegNoList, "Id", "RegNo"), "Student Registration No", new { htmlAttributes = new { @class = "form-control", @id = "RegNo" }, required="" })
                @Html.ValidationMessageFor(model => model.RegNo)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                <input type="text" readonly class="form-control-plaintext" id="StudentName" placeholder="Student Name" required="">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                <input type="text" readonly class="form-control-plaintext" id="StudentEmail" placeholder="Student Email" required="">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                <input type="text" readonly class="form-control-plaintext" id="Department" placeholder="Department" required="">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                @Html.DropDownListFor(model => model.courseId, new SelectList(string.Empty, "CId", "CourseName"), "Courses", new { htmlAttributes = new { @class = "form-control", @id = "courseId" }, required="" })
                @Html.ValidationMessageFor(model => model.courseId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12 input-group">
                @Html.DropDownListFor(model => model.GradeLetter, new SelectList(ViewBag.GradeList, "GradeName", "GradeName"), new { htmlAttributes = new { @class = "form-control", @id = "GradeLetter" }, required="" })
                @Html.ValidationMessageFor(model => model.GradeLetter)
            </div>
        </div>
        

        <div class="form-group">
            <div>
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>


    <script>

	 $(document).ready(function() {

	     $("#RegNo").change(function () {
	         var student = $("#RegNo").val();
	         var jsonData = { RegNo: student };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentById", "StudentResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    dataType: "json",
                    success: function (data) {
                        // alert(data.CreditTaken + " " + data.CreditLeft);
                        $("#StudentName").val(data.Name);
                        $("#StudentEmail").val(data.Email);
			            $("#Department").val(data.DeptName);
                    },

                });
                return false;
            });


	     $("#RegNo").change(function () {

	         var RegId = $("#RegNo").val();

                $("#courseId").empty();
                var json = { RegNo: RegId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCourseByRegId", "StudentResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        //alert(data);
                        $("#courseId").append('<option value=' + 0 + '>' + "Courses" + '</option>');
                        $.each(data, function (key, value) {
                            //alert(key);
                            $("#courseId").append('<option value=' + value.CId + '>' + value.CourseName + '</option>');

                        });
                    }
                });
                return false;
            });


        $("#alert").click(function () {
            $("#alert").hide();


            $("#StudentName").val("");
            $("#StudentEmail").val("");
            $("#Department").val("");
        });


        $("#erroralert").click(function () {
            $("#erroralert").hide();

            $("#RegNo").val("");
            $("#StudentName").val("");
            $("#StudentEmail").val("");
            $("#Department").val("");
        });
            });
    </script>
}