StudentMApp/StudentMApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentMApp.BLL;
using StudentMApp.Model;

namespace StudentMApp.Controllers
{
    public class CourseController : Controller
    {
        DeptManager dmanager = new DeptManager();
        SemesterManager sManager = new SemesterManager();

        CourseManager manager = new CourseManager();
        CAManager caManager = new CAManager();
        TeacherManager tManager = new TeacherManager();

        //
        // GET: /Course/
        public ActionResult Index()
        {
            //Todo: view course statics
            ViewBag.deptList = dmanager.GetAllDept();
            return View();
        }

        [HttpPost]
        public ActionResult Index(int departmentId)
        {
            //Todo: view course statics
            ViewBag.deptList = dmanager.GetAllDept();
            return View();
        }

        //Todo: view course statics
        public JsonResult GetDeptCourse(int departmentId)
        {
            var courses = manager.GetAllCourses();
            var cList = courses.Where(a => a.DeptId == departmentId).ToList();

            foreach (Course course1 in cList)
            {
                if (course1.CourseFlag == 0)
                {
                    course1.TeacherName = "Not assigned yet";
                }
            }
            return Json(cList, JsonRequestBehavior.AllowGet);
        }

        // GET: call when page load
        public ActionResult Save()
        {
            ViewBag.deptList = dmanager.GetAllDept();
            ViewBag.semList = sManager.GetAllInfo();
            return View();
        }

        //POST: call when button click 
        [HttpPost]
        public ActionResult Save(Course crs)
        {
            ViewBag.deptList = dmanager.GetAllDept();
            ViewBag.semList = sManager.GetAllInfo();
            List<Semester> sList = ViewBag.semList;

                if (ModelState.IsValid)
                {
                    ////addition: adding semester name
                    //if (crs.SemesterId != 0)
                    //{
                    //    Semester semester = sList.FirstOrDefault(p => p.SId == crs.SemesterId);
                    //    if (semester != null)
                    //        crs.SemName = semester.SName;
                    //}
                    ////end

                    
                    crs.TeacherId = 0;
                    //crs.TeacherName = ""; // addition: teacher's name
                    crs.CourseFlag = 0;
                    crs.Classflag = 0;

                    string msg = manager.SaveCourse(crs);
                    if (msg == "Saved")
                    {
                        ViewBag.Message = msg;
                    }
                    else
                    {
                        ViewBag.ErrorMessage = msg;
                    }
                }
                else
                {
                    ViewBag.ErrorMessage = "Please enter all information";
                    return View();
                }
            return View();
        }


        // GET: /Unassign Course/
        public ActionResult UnassignCourse()
        {
            //Todo: create confirmation box 
            return View();
        }

        public JsonResult Unassign(bool flag)
        {
            int row1 = 0, row3 = 0;

            if (flag)
            {
                var teacherList = tManager.GetAllTeachers().Where(p => p.TotalCredit > 0).ToList();
                foreach (Teacher teacher in teacherList)
                {
                    teacher.TotalCredit = 0;
                    row1 = tManager.UpdateTeacherStatus(teacher);                
                }

                //var courseAssignList = caManager.GetAllCourses().Where(p => p.Courseflag == 1).ToList();
                //foreach (CourseAssign assign in courseAssignList)
                //{
                //    assign.Courseflag = 0;
                //    row2 = caManager.UpdateCourseStatus(assign);
                //}

                var courseList = manager.GetAllCourses().Where(p => p.CourseFlag == 1).ToList();
                foreach (Course course in courseList)
                {
                    course.CourseFlag = 0;
                    row3 = manager.UpdateCourseFlagStatus(course);
                }

                if (row1 > 0 && row3 > 0)
                {
                    return Json(new { msg = "Successfully unassign all courses" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { msg = "Already unassign all courses" }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { msg = "Failed to unassign" }, JsonRequestBehavior.AllowGet);
            }
            return Json(true);
        }
	}
}

StudentMApp/StudentMApp/Controllers/DeptController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentMApp.BLL;
using StudentMApp.Model;

namespace StudentMApp.Controllers
{
    public class DeptController : Controller
    {
        DeptManager manager = new DeptManager();
        //
        // GET: /Dept
        public ActionResult Index()
        {
            ViewBag.Total = manager.GetAllDept().Count;
            if (manager.GetAllDept() == null)
            {
                ViewBag.msg = "No Data found";
                return View();
            }
            ViewBag.DeptList = manager.GetAllDept();
            return View();
        }

        // GET: call when page load
        public ActionResult Save()
        {
            return View();
        }

        //POST: call when button click
        [HttpPost]
        public ActionResult Save(Department dept)
        {
            if (ModelState.IsValid)
            {
                string msg = manager.Save(dept);

                if (msg == "Saved")
                {
                    ViewBag.Message = msg;
                }
                else
                {
                    ViewBag.ErrorMessage = msg;
                }
            } 
            return View();
        }
    }
}

StudentMApp/StudentMApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentMApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Science_School()
        {
            return View();
        }

        public ActionResult Engg_School()
        {
            return View();
        }

        public ActionResult BA_School()
        {
            return View();
        }

        public ActionResult ASS_School()
        {
            return View();
        }

        public ActionResult USS()
        {
            return View();
        }
    }
}

StudentMApp/StudentMApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentMApp.BLL;
using StudentMApp.Model;

namespace StudentMApp.Controllers
{
    public class StudentController : Controller
    {

        DeptManager dmanager = new DeptManager();
        StudentManager manager = new StudentManager();

        //string RegNo = "";
        
        // GET: /Student/
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Register()
        {
            ViewBag.DeptList = dmanager.GetAllDept(); 
            return View();
        }

        [HttpPost]
        public ActionResult Register(Student student)
        {
            ViewBag.DeptList = dmanager.GetAllDept(); 

            if (ModelState.IsValid)
            {
                student.DeptCode = GetDeptCode(student.DeptId);
                student.DeptName = GetDeptName(student.DeptId);

                student.Year = GetDateYear(student.RegDate);
                student.RegNo = GenerateRegNo(student);
                //RegNo = student.RegNo;

                string testmsg = "";
                Student viewStudent = student;

                testmsg = manager.SaveStudent(student);
                if (testmsg == "Saved")
                {
                    //Todo: go to Index view page and show new student information
                    ViewBag.Message = viewStudent;
                    return View();
                }
                else
                {
                    ViewBag.ErrorMessage = testmsg;
                    return View();
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Please enter all information";
                return View();
            }
            return View();
        }

        private string GetDeptName(int deptId)
        {
            List<Department> deptList = dmanager.GetAllDept();
            string DeptName = "";
            foreach (Department d in deptList)
            {
                if (d.Id == deptId)
                {
                    DeptName = d.Name;
                    break;
                }
            }
            return DeptName;
        }


        private string GetDeptCode(int deptId)
        {
            List<Department> deptList = dmanager.GetAllDept();
            string DeptCode = "";
            foreach (Department d in deptList)
            {
                if (d.Id == deptId)
                {
                    DeptCode = d.Code;
                    break;
                }
            }
            return DeptCode;
        }

        private string GetDateYear(string date)
        {
            string year = date.Substring(6, date.Length-6);
            return year;
        }

        private string GenerateRegNo(Student student)
        {

            string Zero = "";
            List<Student> sList = manager.CountStudent(student.DeptId, student.Year);
            int count = sList.Count + 1;
            int length = 3 - count.ToString().Length;

            for (int i = 0; i < length; i++)
            {
                Zero += "0";
            }

            string RegNo = student.DeptCode + "-" + student.Year + "-" + Zero + count;

            return RegNo;

        }
	}
}

StudentMApp/StudentMApp/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentMApp.BLL;
using StudentMApp.Model;

namespace StudentMApp.Controllers
{
    public class TeacherController : Controller
    {
        DeptManager dmanager = new DeptManager();
        DesignationManager desManager = new DesignationManager();
        TeacherManager manager = new TeacherManager();
        //
        // GET: /Teacher/
        public ActionResult Index()
        {
            ViewBag.TeacherList = manager.GetAllTeachers();

            if (ViewBag.TeacherList == null)
            {
                ViewBag.msg = "No data found";
                return View();
            }
            return View();
        }

        // GET: call when page load
        public ActionResult Save()
        {
            ViewBag.deptList = dmanager.GetAllDept();
            ViewBag.DesignList = desManager.GetAllInfo();
            return View();
        }

        //POST: call when button click  //TODO: check form validation
        [HttpPost]
        public ActionResult Save(Teacher teacher)
        {
            ViewBag.deptList = dmanager.GetAllDept();
            ViewBag.DesignList = desManager.GetAllInfo();
            
            teacher.TotalCredit = 0;
            if (ModelState.IsValid)
            {
                string msg = manager.SaveTeacher(teacher);
                if (msg == "Saved")
                {
                    ViewBag.Message = msg;
                }
                else
                {
                    ViewBag.ErrorMessage = msg;
                }
            }
            else
            {
                ViewBag.ErrorMessage = "Please enter all Information";
                return View();
            }  
            return View();
        }
	}
}

StudentMApp/StudentMApp/Views/Home/ASS_School.cshtml
@{
    ViewBag.Title = "Faculty of Arts and Social Science";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">
    <h3>Departments</h3>
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">English</a></li>
        <li><a data-toggle="tab" href="#menu1">Economics</a></li>
        <li><a data-toggle="tab" href="#menu2">Laws</a></li>
    </ul>
    <br />
    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
            <h3>English</h3>
            <p>The Department of English firmly believes that value-education can bring excellence in leadership, and consequently excellence in nation-building.</p>
        </div>
        <div id="menu1" class="tab-pane fade">
            <h3>Economics</h3>
            <p>The Department of Economics is an integral part of FASS although, the Faculty of Business offers Economics both as minor and majoring the BBA program.</p>
        </div>
        <div id="menu2" class="tab-pane fade">
            <h3>Laws</h3>
            <p>The Department of Laws aims to provide broad education in law and academic disciplines. It aims to develop in students a wide appreciation of relevant subjects and of their importance rigorous academic challenges of current law, and to train them to be excellent law practitioners. This department will provide them the training, which will help them solve the challenging law related problems they encounter. This department also focuses in developing the capabilities to identify and grow new opportunities and integrates theoretical knowledge with the capacity to apply such knowledge in practice and innovation and the practice of innovation leadership.</p>
        </div>
    </div>
</div>

StudentMApp/StudentMApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container-fluid">
    <div class="row">
        <div class="col-sm-10">           
            <h3>About LearnIT University</h3>
            <h4>Lorem ipsum..</h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
        </div>
        <div class="col-sm-2">
            @*<span class="glyphicon glyphicon-signal logo"></span>*@
        </div>
    </div>
</div>

StudentMApp/StudentMApp/Views/Home/BA_School.cshtml
@{
    ViewBag.Title = "Faculty of Business Administration";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">
    <h3>Departments</h3>
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Accounting</a></li>
        <li><a data-toggle="tab" href="#menu1">Finance</a></li>
        <li><a data-toggle="tab" href="#menu2">Marketing</a></li>
    </ul>
    <br />
    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
            <h3>Accounting</h3>
            <p>Accounting – see beyond the numbers’. As a part of its continuous thrives for excellence and with the understanding of the importance of accounting education, LearnIT University has introduced Department of Accounting as an independent department under the Faculty of Business Administration. Since its inception, Department of Accounting has been continuously planning and implementing several strategies to create future Accounting leaders. The holistic approach to accounting education by the Department makes its graduates well conversant with not just technicalities of accounting but also with wider behavioral implications in evolving socio-economic contexts. Moreover, the Department of Accounting is poised to explore new avenues to produce resourceful graduates for employment, both locally and globally, while providing thought leadership in accounting education in Bangladesh. The Department offers a wide range of market oriented courses that will enable students to fulfill information thirst of the organizations through a dynamic and challenging role that will employ them. These courses are conducted by a number of highly qualified faculty members, holding remarkable exposure both in academic and professional arena. The Department has designed both undergraduate [BBA] and graduate [MBA] curriculum to allow students, taking major or minor in Accounting, more flexibility in tailoring their accounting knowledge to meet professional interests and also to provide them an easy access to professional accounting degrees like CA, CMA, ACCA, CIMA etc. We believe that one degree major in accounting will open 360 degrees of possibilities for the students</p>
        </div>
        <div id="menu1" class="tab-pane fade">
            <h3>Finance</h3>
            <p>Department of Finance helps students analyze financing problems happening around the world in various different dimensions. This is further ensured by emphasizing teaching with case studies specific to various nationally and internationally-recognized firms. Moreover, courses are packaged such that students are equipped with knowledge of the cutting-edge research in finance as well as practical work in the field through field visits, study tours, simulated portfolio investment as well as internships. The Department of Finance also helps students to prepare for various professional programs like CFA and CFP. Combined with AIUB’s other departments and programs, the department provides finance students with the choices and resources they need to excel in their academic and professional careers.</p>
        </div>
        <div id="menu2" class="tab-pane fade">
            <h3>Marketing</h3>
            <p>The Marketing Department is a big department with approximately 15 full time faculty members, 500 undergraduate marketing major students, and 200 MBA (Marketing major) students. As a group that is charged with boundary spanning tasks, marketing executives are responsible for listening to their customers, keeping their finger on the pulse of the marketplace, using what they learn to develop products and services that meet (and exceed) customer needs, and staying in touch to keep customers satisfied. More than anything else, modern marketing is about developing innovative solutions to customer problems and taking better care of your customers than your competitors do. Our curriculum and programs are designed to provide our students with the tools and skills they need to be customer-oriented business leaders who are ethically sensitive and globally aware.
</p>
        </div>
    </div>
</div>

StudentMApp/StudentMApp/Views/Home/Engg_School.cshtml
@{
    ViewBag.Title = "Faculty of Engineering";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">
    <h3>Departments</h3>
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Electrical and Electronic Engineering (EEE)</a></li>
        <li><a data-toggle="tab" href="#menu1">Architechture</a></li>
        <li><a data-toggle="tab" href="#menu2">Computer Engineering (CoE)</a></li>
    </ul>
    <br />
    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
            <h3>Electrical and Electronic Engineering (EEE)</h3>
            <p>Electrical and Electronic Engineering is concerned with the design, research, development, planning, manufacture and management of systems and devices relying on electricity and light to transmit data and power which underpin modern economies and contribute to the quality of human life. Many of these devices rely on the use of new information and computer-intensive technologies. An Electrical Engineer may be responsible for research, design, manufacture and operation of communication systems, satellite, microwave, optical, telecommunications, broadcasting, radio and television, solar energy conversion, electric power generation, transmission and distribution, computer networks, microprocessors, instrumentation and consumer devices, automatic control systems and robotics, electronic and integrated circuits, image processing systems, electrical machines, electromechanical equipment, biomedical engineering and many other areas.</p>
            </div>
        <div id="menu1" class="tab-pane fade">
            <h3>Architechture</h3>
            <p>The Department of Architecture offers a five-year program of study leading to the degree of Bachelor of Architecture. The core of the program is the sequence of architecture studio courses in which students produce design solutions of increasing complexity and scope. Studio projects include both abstract and realistic problem solving experiences, and involvement with current theoretical issues related to architectural and environmental design.</p>
        </div>
        <div id="menu2" class="tab-pane fade">
            <h3>Computer Engineering (CoE)</h3>
            <p>A Bachelor of Science in Computer Engineering focuses on the relationship between computer hardware and software systems. Graduates should be prepared to evaluate systems and design efficient solutions to problems.</p><br/>

            <p>A bachelor of science degree in computer engineering typically combines software-related classes in networks, operating systems, programming languages and data structures with hardware-related courses covering microcomputer systems, memory components, microprocessors, fiber optics and integrated circuits. The program meshes formal coursework with practical experience, preparing graduates for a diversity of career options or an advanced degree.</p>
        </div>
    </div>
</div>

StudentMApp/StudentMApp/Views/Home/Science_School.cshtml
@{
    ViewBag.Title = "Faculty of Science and Technology";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">
    <h3>Programs</h3>
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Computer Science and Engineering</a></li>
        <li><a data-toggle="tab" href="#menu1">Computer Science and Software Engineering</a></li>
        <li><a data-toggle="tab" href="#menu2">Software Engineering</a></li>
        <li><a data-toggle="tab" href="#menu3">Computer Science</a></li>
    </ul>
    <br/>
    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
            <h3>Computer Science and Engineering</h3>
            <p>This degree is designed to give you an appreciation of both hardware and software. As with all our degrees we support your learning through the provision of a range of up-to-date computing and electronics laboratories. The first two years of the course give you an introduction to modern computer systems. In the third year you can take specialist courses from a range including Advanced Digital Design, Computer Networks and Computer Architectures. For more info explore <a href="#">BSc CSE Curriculum</a>.</p>
        </div>
        <div id="menu1" class="tab-pane fade">
            <h3>Computer Science and Software Engineering</h3>
            <p>This degree program is designed to feed the need of software engineers who must possess strong programming skills, but are more concerned with developing algorithms and analyzing and solving programming problems than with actually writing code. This mix blend of program will provide you extra confidence in the rapidly evolving software industry. For more info explore <a href="#">BSSE Curriculum</a>.</p>
        </div>
        <div id="menu2" class="tab-pane fade">
            <h3>Software Engineering</h3>
            <p>This degree is designed in response to the growing importance of software to the national infrastructure and the rapid rise in demand for professional software engineers. The curriculum encompasses behavioral, managerial and technical aspects of software engineering and attempts to synthesize disciplinary paradigms and themes. This program is designed specifically for students interested in a range of application domains. We have integrated real-world experiences via the cooperative education program and via team project software development in course work. For more info explore <a href="#">BSSE Curriculum</a>.</p>
        </div>
        <div id="menu3" class="tab-pane fade">
            <h3>Computer Science</h3>
            <p>This degree prepares you to work with the rapidly changing technology of computing by helping you understand the underpinnings of computing science. The first year introduces the core material with an element of individual choice. Thereafter you can continue with mainstream computer science with choices that relate to your interests and career aspirations. In the final year you will work on a project with one of our faculty members on an extended topic under individual supervision. For more info explore <a href="#">BSCS Curriculum</a>.</p>
        </div>
    </div>
</div>

StudentMApp/StudentMApp/Views/Home/USS.cshtml
@{
    ViewBag.Title = "USS";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container text-center">
    <h3>University Management System</h3>
</div>

<div class="container">
    <div class="list-group">
        <a href="#" class="list-group-item list-group-item-action active text-center">Actions</a>
        <a href="@Url.Action("Save", "Dept")" class="list-group-item list-group-item-action">Add New Department</a>
        <a href="@Url.Action("Index", "Dept")" class="list-group-item list-group-item-action">View Departments</a>
        <a href="@Url.Action("Save", "Course")" class="list-group-item list-group-item-action">Add New Course</a>
        <a href="@Url.Action("Save", "Teacher")" class="list-group-item list-group-item-action">Add New Teacher</a>
        <a href="@Url.Action("AssignCourse", "CourseAssign")" class="list-group-item list-group-item-action">Course Assign to Teacher</a>
        <a href="@Url.Action("Index", "Course")" class="list-group-item list-group-item-action">View Course Statics</a>
        <a href="@Url.Action("Register", "Student")" class="list-group-item list-group-item-action">Register Student</a>
        <a href="@Url.Action("AllocateClassroom", "AllocateClass")" class="list-group-item list-group-item-action">Allocate Classrooms</a>
        <a href="@Url.Action("Index", "AllocateClass")" class="list-group-item list-group-item-action">View Class Schedule and Room Allocation Information</a>
        <a href="@Url.Action("EnrollStudent", "EnrollStudent")" class="list-group-item list-group-item-action">Enroll in a Course</a>
        <a href="@Url.Action("StudentResult", "StudentResult")" class="list-group-item list-group-item-action">Save Student Result</a>
        <a href="@Url.Action("Index", "StudentResult")" class="list-group-item list-group-item-action">View Student Result</a>
        <a href="@Url.Action("UnassignCourse", "Course")" class="list-group-item list-group-item-action">Unassign All Courses</a>
        <a href="@Url.Action("UnalloClassroom", "AllocateClass")" class="list-group-item list-group-item-action">Unallocate All Classrooms</a>
    </div>
</div>